name: Example GitHub Actions Workflow  # Workflow name

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Runs for PRs targeting 'main'
  schedule:
    - cron: "0 12 * * 1"  # Runs every Monday at 12:00 UTC
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  example_job:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      # ------------------------------
      # Step 1: Checkout Repository
      # ------------------------------
      - name: Checkout Code
        uses: actions/checkout@v3

      # ------------------------------
      # Step 2: Set Up Node.js Environment (Conditional)
      # ------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        if: ${{ true }}  # Ensures the step always evaluates to true unless overridden

      # ------------------------------
      # Step 3: Install Dependencies (Runs only if package.json exists)
      # ------------------------------
      - name: Install Dependencies
        run: npm install
        if: ${{ hashFiles('package.json') != '' }}  # Runs only if package.json exists

      # ------------------------------
      # Step 4: Run Tests (Runs only if tests exist)
      # ------------------------------
      - name: Run Tests
        run: npm test
        if: ${{ hashFiles('tests/**') != '' }}  # Runs only if there are test files

      # ------------------------------
      # Step 5: Deploy Code (Runs only if on 'main' branch)
      # ------------------------------
      - name: Deploy to Production
        shell: bash-wrapper {0}
        run: |
           bash deploy.sh
        if: ${{ github.ref == 'refs/heads/main' }}  # Runs only if on main branch
        continue-on-error: true  # Prevents failure if deployment conditions are unmet

  # ------------------------------
  # Parallel Job Example
  # ------------------------------
  another_job:
    runs-on: ubuntu-latest
    needs: example_job  # Runs after 'example_job' completes
    steps:
      - name: Echo Message
        run: echo "This job runs after 'example_job'"
